// Writes src/version.js from git state, so the running page can say exactly
// which commit it is. Without this, "did my deploy land?" needs a curl and a
// diff — and a stale cache looks identical to a broken feature.
import {execSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';

const sha = execSync('git rev-parse --short HEAD').toString().trim();
const dirty = execSync('git status --porcelain').toString().trim().length > 0;
const built = new Date().toISOString();

writeFileSync('src/version.js',
  `// Generated by scripts-stamp.mjs — do not edit by hand.\n` +
  `export const BUILD = ${JSON.stringify(`${sha}${dirty ? '+dirty' : ''}`)};\n` +
  `export const BUILT_AT = ${JSON.stringify(built)};\n`);

console.log(`stamped ${sha}${dirty ? '+dirty' : ''} @ ${built}`);
